import {useEffect,useState,type FormEvent} from 'react';
import {Link,useParams,useLocation} from 'react-router-dom';
import {useAuth} from '../auth';
import {useResource,mutation} from '../lib/resource';
import {request,errorMessage} from '../api/client';
import type {Machine,Document} from '../types/registry';
import {Card,SectionTitle} from '../components/ui/Card';
import {Button} from '../components/ui/Button';
import {Alert} from '../components/ui/Alert';
const types=['manual','sop','maintenance_guide','troubleshooting_guide','spec_sheet','other'];
function ScopePicker({scope,targets,machines,onChange}:{scope:string;targets:string[];machines:Machine[];onChange:(s:string,t:string[])=>void}){const opts=scope==='machine'?machines.map(m=>m.machine_uid):scope==='model'?[...new Set(machines.map(m=>m.model))]:scope==='line'?[...new Set(machines.map(m=>m.line))]:[];return <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Scope<select className="field mt-1" value={scope} onChange={e=>onChange(e.target.value,[])}>{['machine','model','line','plant'].map(s=><option key={s}>{s}</option>)}</select></label>{scope!=='plant'&&<label className="text-sm">Targets (Ctrl / Command to select several)<select multiple required className="field mt-1" value={targets} onChange={e=>onChange(scope,Array.from(e.target.selectedOptions,o=>o.value))}>{opts.map(o=><option key={o}>{o}</option>)}</select></label>}</div>;}
function Detection({doc}:{doc:Document}){return <div className="space-y-3">{doc.detection.warnings.map((w,i)=><Alert key={i} tone="warning" title="Mapping review">{w}</Alert>)}{doc.detection.ambiguities.map((a,i)=><p key={i} className="text-sm">{a.short_name} is ambiguous: {a.candidates.join(', ')}. Suggested model scope: {a.model_scopes.join(', ')}.</p>)}<details><summary className="cursor-pointer text-sm font-semibold text-indigo-700">Detection suggestions</summary><ul className="mt-3 space-y-2 text-sm">{doc.detection.suggestions.map((s,i)=><li key={i}>{s.target} · {s.scope} · {s.confidence} · {s.location} · matched {s.matched_terms.join(', ')}</li>)}</ul></details></div>;}
export function DocumentsPage(){const {can}=useAuth();const[rev,setRev]=useState(0),[machine,setMachine]=useState(''),[type,setType]=useState(''),[status,setStatus]=useState(''),[scope,setScope]=useState('plant'),[targets,setTargets]=useState<string[]>([]),[failure,setFailure]=useState(''),[busy,setBusy]=useState(false),[uploaded,setUploaded]=useState<Document|null>(null);
 const {data:machines}=useResource<Machine[]>('/api/machines');const query=new URLSearchParams();if(machine)query.set('machine_uid',machine);if(type)query.set('doc_type',type);if(status)query.set('status',status);const {data:docs,error}=useResource<Document[]>('/api/documents?'+query,rev);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setFailure('');const form=e.currentTarget;const body=new FormData(form);body.set('scope',scope);body.set('targets',JSON.stringify(targets));try{const d=await request<Document>('/api/documents/upload',{method:'POST',body});setUploaded(d);setRev(n=>n+1);form.reset();}catch(err){setFailure(errorMessage(err));}finally{setBusy(false);}};
 return <div className="space-y-6"><SectionTitle title="Document library" sub="Active scoped documents support RCA. Pending mappings need confirmation."/>{(error||failure)&&<Alert tone="danger" title="Documents">{error||failure}</Alert>}
 {can('documents')&&<details className="rounded-lg border border-slate-200 bg-white p-6"><summary className="cursor-pointer font-bold text-indigo-700">Upload machine documentation</summary><form onSubmit={submit} className="mt-6 space-y-4"><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Title<input required name="title" className="field mt-1"/></label><label className="text-sm">Type<select name="doc_type" className="field mt-1">{types.map(t=><option key={t}>{t}</option>)}</select></label><label className="text-sm">Version<input required name="version" className="field mt-1" defaultValue="1"/></label></div><ScopePicker scope={scope} targets={targets} machines={machines||[]} onChange={(s,t)=>{setScope(s);setTargets(t);}}/><label className="block text-sm">PDF, DOCX, Markdown or TXT<input required name="file" type="file" accept=".pdf,.docx,.md,.txt" className="field mt-2"/></label><Button type="submit" loading={busy} arrow>Upload document</Button></form></details>}
 {uploaded&&<Card className="space-y-3 p-5"><p>Uploaded <Link to={'/documents/'+uploaded.doc_id} className="font-semibold text-indigo-700">{uploaded.title}</Link> · {uploaded.status}</p><Detection doc={uploaded}/>{uploaded.status==='pending_mapping'&&<Button to={'/documents/'+uploaded.doc_id}>Review and confirm mapping</Button>}</Card>}
 <div className="grid gap-3 sm:grid-cols-3"><select aria-label="Filter by machine" className="field" value={machine} onChange={e=>setMachine(e.target.value)}><option value="">All machines</option>{machines?.map(m=><option key={m.machine_uid}>{m.machine_uid}</option>)}</select><select aria-label="Filter by type" className="field" value={type} onChange={e=>setType(e.target.value)}><option value="">All document types</option>{types.map(t=><option key={t}>{t}</option>)}</select><select aria-label="Filter by status" className="field" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{['active','pending_mapping','archived'].map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{docs?.map(d=><Card className="p-5" key={d.doc_id}><Link className="font-bold text-indigo-700" to={'/documents/'+d.doc_id}>{d.title}</Link><p className="mt-3 text-sm">{d.doc_type} · v{d.version}</p><p className="mt-2 text-sm"><span className="rounded-full bg-indigo-50 px-2 py-1 text-indigo-700">{d.scope}</span> · {d.status}</p><p className="mt-3 break-words text-xs">{d.targets.join(', ')||'Plant-wide'}</p></Card>)}</div>{docs?.length===0&&<p>No documents match these filters.</p>}</div>;
}
export function DocumentPage(){const {id}=useParams(),location=useLocation(),{can}=useAuth();const[rev,setRev]=useState(0),[scope,setScope]=useState(''),[targets,setTargets]=useState<string[]>([]),[failure,setFailure]=useState('');const{data:doc,error}=useResource<Document>('/api/documents/'+id,rev),{data:machines}=useResource<Machine[]>('/api/machines');
 const actualScope=scope||doc?.scope||'plant',actualTargets=scope?targets:doc?.targets||[];
 const [title,setTitle]=useState('');
 useEffect(()=>{if(doc&&location.hash)document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView({block:'center'});},[doc,location.hash]);
 const saveMetadata=async()=>{try{await mutation('/api/documents/'+id,{scope:actualScope,targets:actualTargets,title:title||doc?.title,doc_type:doc?.doc_type},'PATCH');setRev(n=>n+1);}catch(e){setFailure(errorMessage(e));}};
 const confirm=async()=>{try{await mutation('/api/documents/'+id+'/confirm',{scope:actualScope,targets:actualTargets});setRev(n=>n+1);}catch(e){setFailure(errorMessage(e));}};
 const archive=async()=>{try{await mutation('/api/documents/'+id,{scope:actualScope,targets:actualTargets,status:'archived'},'PATCH');setRev(n=>n+1);}catch(e){setFailure(errorMessage(e));}};
 return <div className="space-y-6"><Button to="/documents" variant="ghost">Document library</Button><SectionTitle title={doc?.title||'Document'}/>{(error||failure)&&<Alert tone="danger" title="Document">{error||failure}</Alert>}{doc&&<><Card className="space-y-4 p-6"><p>{doc.doc_id} · v{doc.version} · {doc.doc_type} · {doc.scope} · {doc.status}</p><p className="text-sm">Targets: {doc.targets.join(', ')||'Plant-wide'} · uploaded {new Date(doc.uploaded_at).toLocaleString()}</p><Detection doc={doc}/>{can('documents')&&<div className="space-y-4 border-t border-slate-200 pt-5"><h3 className="font-bold text-ink-900">Review mapping</h3><label className="block text-sm">Document title<input className="field mt-1" value={title||doc.title} onChange={e=>setTitle(e.target.value)}/></label><Button variant="outline" onClick={()=>void saveMetadata()}>Save title and request review</Button><ScopePicker scope={actualScope} targets={actualTargets} machines={machines||[]} onChange={(s,t)=>{setScope(s);setTargets(t);}}/><p className="text-sm">Confirmation acknowledges any ambiguity or conflict shown above.</p><div className="flex flex-wrap gap-3"><Button onClick={()=>void confirm()}>Confirm mapping and activate</Button><Button variant="outline" onClick={()=>void archive()}>Archive document</Button></div></div>}</Card><SectionTitle title="Pages and sections"/>{doc.chunks?.map(c=><Card key={c.chunk_id} className={'scroll-mt-32 p-6 '+(decodeURIComponent(location.hash.slice(1))===c.chunk_id?'border-2 border-indigo-500':'')}><h3 id={c.chunk_id} className="font-bold text-ink-900">{c.page_or_section}</h3><p className="mt-1 break-all font-mono text-xs">{c.chunk_id}</p><p className="mt-4 whitespace-pre-wrap leading-relaxed">{c.text}</p></Card>)}</>}</div>;
}
