import {useState} from 'react';
import {useAuth} from '../auth';
import {useResource,mutation} from '../lib/resource';
import {errorMessage} from '../api/client';
import type {EvalRun} from '../types/registry';
import {Card,SectionTitle} from '../components/ui/Card';
import {Button} from '../components/ui/Button';
import {Alert} from '../components/ui/Alert';
export function EvaluationsPage(){const{can}=useAuth(),[rev,setRev]=useState(0),[failure,setFailure]=useState(''),[busy,setBusy]=useState(false);const{data,error}=useResource<EvalRun>('/api/evals',rev);const run=async()=>{setBusy(true);setFailure('');try{await mutation('/api/evals/run',{});setRev(n=>n+1);}catch(e){setFailure(errorMessage(e));}finally{setBusy(false);}};return <div className="space-y-6"><SectionTitle title="Evaluation results" sub="Deterministic regression suites; optional live judge reported separately." right={can('evals')?<Button loading={busy} onClick={()=>void run()} arrow>Run evaluations</Button>:undefined}/>{(error||failure)&&<Alert tone="danger" title="Evaluations">{error||failure}</Alert>}{data&&!data.run_id&&<Card className="p-6">No evaluation run yet. An administrator or QA lead can start one.</Card>}{data?.run_id&&<><p className="text-sm">Last run: {new Date(data.created_at||'').toLocaleString()}</p><details><summary className="cursor-pointer text-sm font-semibold">Run configuration</summary><pre className="mt-3 overflow-auto rounded-md bg-white p-4 text-xs">{JSON.stringify(data.config,null,2)}</pre></details>{data.suites.map(s=><section key={s.suite} className="space-y-4"><SectionTitle title={s.suite}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{s.metrics.map(m=><Card className="p-5" key={m.metric}><p className="text-xs font-semibold">{m.metric.replaceAll('_',' ')}</p><p className="mt-3 text-3xl font-bold text-indigo-700">{m.value===null?'Unverified':Number(m.value.toFixed(4))}</p><p className="mt-2 text-sm">{m.passed===null?m.status||'Skipped':m.passed?'Pass':'Fail'} · threshold {m.threshold??'—'}</p></Card>)}</div><details className="rounded-lg border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-semibold">Per-case details ({s.details.length})</summary><div className="mt-4 overflow-auto"><table className="w-full text-left text-xs"><tbody>{s.details.map((r,i)=><tr key={i} className="border-t border-slate-200">{Object.entries(r).map(([k,v])=><td className="max-w-xl break-words p-3" key={k}><span className="font-semibold">{k}: </span>{typeof v==='object'?JSON.stringify(v):String(v)}</td>)}</tr>)}</tbody></table></div></details></section>)}</>}</div>;}
