import {useState,type FormEvent} from 'react';
import {Navigate,useNavigate} from 'react-router-dom';
import {useAuth} from '../auth';
import {Button} from '../components/ui/Button';
import {Alert} from '../components/ui/Alert';
import {errorMessage} from '../api/client';
export function LoginPage(){const {user,login}=useAuth(),navigate=useNavigate();const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(user)return <Navigate to="/" replace/>;
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await login(email,password);navigate('/');}catch(err){setError(errorMessage(err));}finally{setBusy(false);}};
 return <main className="relative flex min-h-screen items-center justify-center overflow-hidden bg-white p-4 sm:p-8"><div aria-hidden className="pointer-events-none absolute h-[720px] w-[720px] opacity-50 blur-[48px]" style={{background:'var(--g-aura)'}}/>
 <div className="relative grid w-full max-w-[1080px] overflow-hidden rounded-xl border border-slate-200 bg-white shadow-hover md:grid-cols-2">
 <section className="space-y-6 bg-indigo-50/70 p-8 sm:p-12"><p className="font-bold text-indigo-700">Production Intelligence & RCA</p><h1 className="text-4xl font-bold leading-tight text-ink-900">Read every signal.<br/><span className="text-indigo-700">Investigate every</span><br/><span className="text-teal-500">hypothesis.</span></h1><div className="flex h-48 items-center justify-center rounded-xl border border-dashed border-indigo-500 bg-white/60 p-6 text-center text-sm text-indigo-700">Robot placeholder<br/>Reserved for a future auth illustration</div><div className="space-y-2 text-sm"><p>Detect · Production signal deviations</p><p>Investigate · Evidence-ranked hypotheses</p><p>Learn · QA-approved experience</p></div></section>
 <section className="p-8 sm:p-12"><p className="text-sm font-semibold text-indigo-700">Plant access</p><h2 className="mt-3 text-3xl font-bold text-ink-900">Welcome back</h2><p className="mt-3">Sign in to investigate incidents on the line.</p><form onSubmit={submit} className="mt-8 space-y-5"><label className="block text-sm font-semibold">Email<input className="field mt-2" type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block text-sm font-semibold">Password<input className="field mt-2" type={show?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/>Show password</label><div className="flex flex-wrap gap-2">{[['Plant engineer','engineer'],['QA lead','qa'],['Viewer','viewer']].map(([label,name])=><Button key={name} type="button" size="sm" variant="outline" onClick={()=>setEmail(name+'@demo.local')}>{label}</Button>)}</div><p className="text-xs">Demo passwords come from DEMO_PASSWORD. Accounts are created by your administrator.</p>{error&&<Alert tone="danger" title="Sign in failed">{error}</Alert>}<Button type="submit" loading={busy} arrow className="w-full">Open dashboard</Button></form></section>
 </div></main>;
}
