import {useState,type FormEvent} from 'react';
import {Link,useParams} from 'react-router-dom';
import {useAuth} from '../auth';
import {useResource,mutation} from '../lib/resource';
import {errorMessage} from '../api/client';
import type {Machine,Document} from '../types/registry';
import type {IncidentRow} from '../types/workflow';
import {StatusBadge} from '../components/ui/StatusBadge';
import {Card,SectionTitle} from '../components/ui/Card';
import {Button} from '../components/ui/Button';
import {Alert} from '../components/ui/Alert';
export function MachinesPage(){const {data,error}=useResource<Machine[]>('/api/machines');return <div className="space-y-6"><SectionTitle title="Machines" sub="Physical machines across LINE-A, LINE-B and LINE-C."/>{error&&<Alert tone="danger" title="Machines unavailable">{error}</Alert>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{data?.map(m=><Card key={m.machine_uid} className="p-6"><Link className="font-mono font-bold text-indigo-700" to={'/machines/'+m.machine_uid}>{m.machine_uid}</Link><p className="mt-3">{m.display_name}</p><p className="mt-2 text-sm">{m.line} · model {m.model}</p><div className="mt-3 flex gap-3 text-sm"><span className="rounded-full bg-mint-100 px-3 py-1 text-success-ink">{m.status}</span><span>{m.doc_count} linked documents</span></div></Card>)}</div>{!data&&!error&&<p>Loading machines…</p>}</div>;}
export function MachinePage(){const {line,short}=useParams(),uid=line+'/'+short,{can}=useAuth();const[rev,setRev]=useState(0),[editing,setEditing]=useState(false),[draft,setDraft]=useState<Machine|null>(null),[ranges,setRanges]=useState(''),[failure,setFailure]=useState('');
 const {data:m,error}=useResource<Machine>('/api/machines/'+uid,rev),{data:docs}=useResource<Document[]>('/api/machines/'+uid+'/documents',rev),{data:incidents}=useResource<IncidentRow[]>('/api/machines/'+uid+'/incidents');
 const save=async(e:FormEvent)=>{e.preventDefault();try{await mutation('/api/machines/'+uid,{...draft,normal_ranges:JSON.parse(ranges)},'PATCH');setEditing(false);setRev(n=>n+1);}catch(err){setFailure(errorMessage(err));}};
 return <div className="space-y-6"><Button to="/machines" variant="ghost">All machines</Button><SectionTitle title={uid} right={can('machines')&&m?<Button onClick={()=>{setDraft(m);setRanges(JSON.stringify(m.normal_ranges,null,2));setEditing(true);}}>Edit machine</Button>:undefined}/>{(error||failure)&&<Alert tone="danger" title="Machine update">{error||failure}</Alert>}
 {editing&&draft&&<Card className="p-6"><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2">{(['display_name','type','manufacturer','model','serial_number','install_date','status'] as const).map(key=><label key={key} className="text-sm">{key.replaceAll('_',' ')}<input className="field mt-1" value={draft[key]||''} onChange={e=>setDraft({...draft,[key]:e.target.value||(key==='serial_number'||key==='install_date'?null:'')})}/></label>)}</div><label className="block text-sm">Normal operating ranges (min / normal / max)<textarea className="field mt-2 font-mono" rows={10} value={ranges} onChange={e=>setRanges(e.target.value)}/></label><div className="flex gap-3"><Button type="submit">Save</Button><Button type="button" variant="outline" onClick={()=>setEditing(false)}>Cancel</Button></div></form></Card>}
 {m&&<Card className="p-6"><div className="grid gap-4 sm:grid-cols-3">{Object.entries(m).filter(([k])=>!['normal_ranges','range_provenance','doc_count'].includes(k)).map(([k,v])=><div key={k}><p className="text-xs text-slate-500">{k.replaceAll('_',' ')}</p><p className="mt-1 break-all font-semibold text-ink-900">{String(v??'Not recorded')}</p></div>)}</div><h3 className="mt-8 font-bold text-ink-900">Normal operating ranges</h3><div className="mt-3 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{['Signal','Min','Normal','Max'].map(k=><th className="p-2" key={k}>{k}</th>)}</tr></thead><tbody>{Object.entries(m.normal_ranges).map(([sig,r])=><tr key={sig} className="border-t border-slate-200"><td className="p-2 font-mono">{sig}</td>{[r.min,r.normal,r.max].map((v,i)=><td key={i} className="p-2 font-mono">{v}</td>)}</tr>)}</tbody></table></div><p className="mt-4 text-xs">{m.range_provenance}</p></Card>}
 <SectionTitle title="Linked documents"/><div className="grid gap-3 sm:grid-cols-2">{docs?.map(d=><Card key={d.doc_id} className="p-4"><Link to={'/documents/'+d.doc_id} className="font-semibold text-indigo-700">{d.title}</Link><p className="mt-2 text-sm">{d.scope} · {d.status} · v{d.version}</p></Card>)}</div><SectionTitle title="Related incidents" sub="Incidents where this machine deviated or is the hypothesis target."/><div className="flex flex-wrap gap-3">{incidents?.map(i=><Link key={i.id} to={'/incidents/'+i.id} className="flex items-center gap-2 rounded-full border border-slate-200 bg-white px-3 py-1.5 font-mono text-sm font-semibold text-indigo-700 hover:bg-indigo-50">{i.id}<StatusBadge status={i.status}/></Link>)}{incidents?.length===0&&<p className="text-sm">No incidents affected this machine.</p>}</div></div>;
}
