import {useState,type FormEvent} from 'react';
import {useAuth,type User,type Role} from '../auth';
import {useResource,mutation} from '../lib/resource';
import {errorMessage} from '../api/client';
import type {Case} from '../types/registry';
import {Card,SectionTitle} from '../components/ui/Card';
import {Button} from '../components/ui/Button';
import {Alert} from '../components/ui/Alert';
export function CasesPage(){const{can}=useAuth(),[rev,setRev]=useState(0),[status,setStatus]=useState(''),[failure,setFailure]=useState('');const{data:cases,error}=useResource<Case[]>('/api/cases'+(status?'?status='+status:''),rev);const review=async(id:string,action:string)=>{try{await mutation('/api/cases/'+id+'/'+action,{});setRev(n=>n+1);}catch(e){setFailure(errorMessage(e));}};
 return <div className="space-y-6"><SectionTitle title="Experience memory" sub="Proposals become recallable after QA or administrator approval. Seed cases are synthetic."/><select className="field max-w-xs" aria-label="Case status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All cases</option>{['proposed','approved','rejected'].map(s=><option key={s}>{s}</option>)}</select>{(error||failure)&&<Alert tone="danger" title="Case review">{error||failure}</Alert>}<div className="grid gap-4 md:grid-cols-2">{cases?.map(c=><Card key={c.case_id} className="space-y-3 p-6"><p className="break-all font-mono text-xs">{c.case_id}</p><h3 className="font-bold text-ink-900">{c.confirmed_category}{c.confirmed_subcause?' / '+c.confirmed_subcause:''}</h3><p className="text-sm"><span className="rounded-full bg-indigo-50 px-2 py-1 text-indigo-700">{c.status}</span> · {c.label}</p><p>{c.summary}</p><p className="text-sm">{c.machine_uid||c.line}</p><p className="text-sm"><strong>Fix applied:</strong> {c.fix_applied}</p>{c.lessons&&<p className="text-sm"><strong>Lessons:</strong> {c.lessons}</p>}<p className="text-xs">Proposer: {c.proposer_id||'synthetic seed'} · Reviewer: {c.approver_id||'pending / seed'}</p>{can('approve')&&c.status==='proposed'&&<div className="flex gap-3"><Button onClick={()=>void review(c.case_id,'approve')}>Approve</Button><Button variant="outline" onClick={()=>void review(c.case_id,'reject')}>Reject</Button></div>}</Card>)}</div></div>;
}
const roles:Role[]=['admin','engineer','qa_lead','viewer'];
export function UsersPage(){const[rev,setRev]=useState(0),[failure,setFailure]=useState(''),[busy,setBusy]=useState(false);const{data:users,error}=useResource<User[]>('/api/users',rev);const change=async(id:string,body:unknown)=>{try{await mutation('/api/users/'+id,body,'PATCH');setRev(n=>n+1);}catch(e){setFailure(errorMessage(e));}};const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const form=e.currentTarget;try{await mutation('/api/users',Object.fromEntries(new FormData(form)));form.reset();setRev(n=>n+1);}catch(e){setFailure(errorMessage(e));}finally{setBusy(false);}};
 return <div className="space-y-6"><SectionTitle title="User administration"/>{(error||failure)&&<Alert tone="danger" title="User update">{error||failure}</Alert>}<Card className="p-6"><form onSubmit={create} className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><label className="text-sm">Email<input type="email" name="email" required className="field mt-1"/></label><label className="text-sm">Initial password<input type="password" name="password" required minLength={10} className="field mt-1" autoComplete="new-password"/></label><label className="text-sm">Role<select name="role" className="field mt-1">{roles.map(r=><option key={r}>{r}</option>)}</select></label><Button type="submit" loading={busy} className="self-end">Create user</Button></form></Card><div className="space-y-3">{users?.map(u=><Card key={u.id} className="flex flex-wrap items-center gap-4 p-5"><p className="min-w-0 flex-1 break-all font-semibold text-ink-900">{u.email}</p><select aria-label={'Role for '+u.email} value={u.role} className="field max-w-48" onChange={e=>void change(u.id,{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select><Button variant="outline" onClick={()=>void change(u.id,{active:!u.active})}>{u.active?'Deactivate':'Activate'}</Button></Card>)}</div></div>;
}
