import {useState,type FormEvent} from 'react';
import {type User,type Role} from '../auth';
import {useResource,mutation} from '../lib/resource';
import {errorMessage} from '../api/client';
import {Card,SectionTitle} from '../components/ui/Card';
import {Button} from '../components/ui/Button';
import {Alert} from '../components/ui/Alert';
const roles:Role[]=['admin','engineer','qa_lead','viewer'];
export function UsersPage(){const[rev,setRev]=useState(0),[failure,setFailure]=useState(''),[busy,setBusy]=useState(false);const{data:users,error}=useResource<User[]>('/api/users',rev);const change=async(id:string,body:unknown)=>{try{await mutation('/api/users/'+id,body,'PATCH');setRev(n=>n+1);}catch(e){setFailure(errorMessage(e));}};const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const form=e.currentTarget;try{await mutation('/api/users',Object.fromEntries(new FormData(form)));form.reset();setRev(n=>n+1);}catch(e){setFailure(errorMessage(e));}finally{setBusy(false);}};
 return <div className="space-y-6"><SectionTitle title="User administration"/>{(error||failure)&&<Alert tone="danger" title="User update">{error||failure}</Alert>}<Card className="p-6"><form onSubmit={create} className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><label className="text-sm">Email<input type="email" name="email" required className="field mt-1"/></label><label className="text-sm">Initial password<input type="password" name="password" required minLength={10} className="field mt-1" autoComplete="new-password"/></label><label className="text-sm">Role<select name="role" className="field mt-1">{roles.map(r=><option key={r}>{r}</option>)}</select></label><Button type="submit" loading={busy} className="self-end">Create user</Button></form></Card><div className="space-y-3">{users?.map(u=><Card key={u.id} className="flex flex-wrap items-center gap-4 p-5"><p className="min-w-0 flex-1 break-all font-semibold text-ink-900">{u.email}</p><select aria-label={'Role for '+u.email} value={u.role} className="field max-w-48" onChange={e=>void change(u.id,{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select><Button variant="outline" onClick={()=>void change(u.id,{active:!u.active})}>{u.active?'Deactivate':'Activate'}</Button></Card>)}</div></div>;
}
